### ISSUE TITLE
Issue with running the code in ubuntu 20 with python3

### ISSUE THREAD

**Issue by Beesh1** [MAN1986/pyamaze#1]
File "/usr/lib/python3.8/tkinter/__init__.py", line 2220, in wm_state
    return self.tk.call('wm', 'state', self._w, newstate)
_tkinter.TclError: bad argument "zoomed": must be normal, iconic, or withdrawn

**Comment by MAN1986** [comment]
Can you check by removing line number 622 which is :
self._win.state('zoomed')

Apparently it seems that state zoomed is not working for ubuntu.

**Comment by Beesh1** [comment]
it worked by removing the word 'zoomed' and replacing it with 'normal'
